### ISSUE TITLE
[error]The $pubspecFilePath does not contain a "flutter" key. ```

### ISSUE THREAD

**Issue by romanr** [zgosalvez/github-actions-get-flutter-version-env#102]
build log:

```
2:  Ubuntu
...

105:  branch 'develop' set up to track 'origin/develop'.
106:  ##[endgroup]
107:  [command]/usr/bin/git log -1 --format='%H'
108:  'xx'
109:  ##[group]Run zgosalvez/github-actions-get-flutter-version-env@v2
110:  with:
111:  pubspec-file-path: pubspec.yaml
112:  ##[endgroup]
113:  ##[error]The $pubspecFilePath does not contain a "flutter" key.
```

CI File fragment:
```
  buildAndroid:
    name: 🤖 Build Android
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4
        with:
          ref: develop
      - name: Get Flutter version
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v2
      - name: ⚙️ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
```

pubspec.yaml:

```yml
name: test
description: Test

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2023.0.1+1

environment:
  # Dart
  sdk: 3.3.0
  # Flutter SDK
  flutter: 3.19.2

# Flavor config
flavorizr:
  ide: 'idea'
```
